language: common-lisp

env:
  global:
    - PATH=~/.roswell/bin:~/nginx/sbin:$PATH
    - LD_LIBRARY_PATH=$HOME/libuv/lib:$LD_LIBRARY_PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERALLS=true
    - LISP=ccl-bin
    - LISP=abcl
    - LISP=ecl
    #- LISP=clisp

install:
  # Install Roswell
  - curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
  - ros asdf install
  - ros -e '(ql:update-all-dists :prompt nil)'
  - ros install prove

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

before_script:
  - ros --version
  - ros config
  - ros -e '(princ (lisp-implementation-type))
            (terpri)
            (princ (lisp-implementation-version))
            (terpri)
            (princ *features*)
            (terpri)'

script:
  - "[[ $COVERALLS == true ]] && run-prove cl-fixtures-test.asd || ros -l cl-fixtures.asd -l cl-fixtures-test.asd -e '(ql:quickload :cl-fixtures-test) (ql:quickload :prove) (uiop:quit (if (prove:run-test-system :cl-fixtures-test) 0 1))'"
